# Generated by Django 5.0.4 on 2024-04-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0008_alter_cost_date_alter_income_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
    ]
